AMP_VERBOSE: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  NUM_WORKERS: 16
  PIN_MEMORY: false
  SIZE_DIVISIBILITY: 32
DATASETS:
  TEST:
  - VID_gaode_4_val
  TRAIN:
  - VID_gaode_4_train_2
DTYPE: float32
INPUT:
  BRIGHTNESS: 0.166
  CONTRAST: 0.5
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  HUE: 0.5
  INFER_BATCH: 8
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 600
  MIN_SIZE_TRAIN:
  - 600
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  RANROM_CROP_MAX_RATIO_TRAIN: 2.0
  RANROM_CROP_MAX_SIZE_TRAIN: 1.0
  RANROM_CROP_MIN_SIZE_TRAIN: 0.3
  RANROM_CROP_PROB_TRAIN: 0.5
  RANROM_PAD_PROB_TRAIN: 0.5
  RANROM_PAD_SIZE_TRAIN: 1.0
  SATURATION: 0.5
  TO_BGR255: false
  TRANSFORM: true
  VERTICAL_FLIP_PROB_TRAIN: 0.0
MODEL:
  BACKBONE:
    CONV_BODY: R-101-torchvision
    FREEZE_AT: 2
    FREEZE_CONV_BODY_AT: 2
    NAME: build_resnet_fpn_backbone
  CLS_AGNOSTIC_BBOX_REG: false
  DEVICE: cuda
  DiffusionDet:
    ACTIVATION: relu
    ALPHA: 0.25
    CLASS_WEIGHT: 2.0
    DEEP_SUPERVISION: true
    DIM_DYNAMIC: 64
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.0
    GAMMA: 2.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    L1_WEIGHT: 5.0
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1
    NUM_CLASSES: 11
    NUM_CLS: 1
    NUM_DYNAMIC: 2
    NUM_HEADS: 3
    NUM_HEADS_LOCAL: 1
    NUM_PROPOSALS: 300
    NUM_REG: 3
    OTA_K: 5
    PRIOR_PROB: 0.01
    SAMPLE_STEP: 1
    SNR_SCALE: 2.0
    USE_FED_LOSS: false
    USE_FOCAL: true
    USE_NMS: true
  FBNET:
    ARCH: default
    ARCH_DEF: ''
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: true
    DW_CONV_SKIP_RELU: true
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: ''
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
    - res3
    - res4
    - res5
    NORM: ''
    OUT_CHANNELS: 256
    USE_GN: false
    USE_RELU: false
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1.0e-05
    NUM_GROUPS: 32
  KEYPOINT_ON: false
  MASK_ON: false
  META_ARCHITECTURE: DiffusionDet
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    DEFORMABLE_GROUPS: 1
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 101
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: false
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: false
  RETINANET:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDES:
    - 8
    - 16
    - 32
    - 64
    - 128
    ASPECT_RATIOS: &id002
    - 0.5
    - 1.0
    - 2.0
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.4
    NUM_CLASSES: 81
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: true
  RETINANET_ON: false
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 31
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: &id001
    - 0.0625
    POOLER_TYPE: ROIAlignV2
    PREDICTOR: FastRCNNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 300
    FG_IOU_THRESHOLD: 0.5
    IN_FEATURES:
    - p3
    - p4
    - p5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.001
    USE_FPN: false
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: *id001
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
  ROI_MASK_HEAD:
    CONV_LAYERS:
    - 256
    - 256
    - 256
    - 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: *id001
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_GN: false
  RPN:
    ANCHOR_SIZES:
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDE:
    - 16
    ASPECT_RATIOS: *id002
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: true
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 300
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 6000
    RPN_HEAD: SingleConvRPNHead
    STRADDLE_THRESH: 0
    USE_FPN: false
  RPN_ONLY: false
  SWIN:
    OUT_FEATURES:
    - 0
    - 1
    - 2
    - 3
    SIZE: B
    USE_CHECKPOINT: false
  VID:
    DFF:
      MAX_OFFSET: 0
      MIN_OFFSET: -9
    ENABLE: true
    FGFA:
      ALL_FRAME_INTERVAL: 19
      KEY_FRAME_LOCATION: 9
      MAX_OFFSET: 9
      MIN_OFFSET: -9
      REF_NUM: 2
    FLOWNET_WEIGHT: models/flownet.ckpt
    IGNORE: false
    MEGA:
      ALL_FRAME_INTERVAL: 8
      GLOBAL:
        BOX_ATTEND: true
        ENABLE: true
        PIXEL_ATTEND: false
        PIXEL_STAGE: 0
        RES_STAGE: 1
        SHUFFLE: true
        SIZE: 24
        STOP_UPDATE_AFTER_INIT_TEST: true
      KEY_FRAME_LOCATION: 0
      LOCAL:
        ENABLE: false
        PIXEL_ATTEND: false
      MAX_OFFSET: 7
      MEMORY:
        ENABLE: false
        SIZE: 25
      MEMORY_MANAGEMENT_METRIC: distance
      MEMORY_MANAGEMENT_SIZE_PIXEL_TEST: 1000
      MEMORY_MANAGEMENT_SIZE_PIXEL_TRAIN: 3000
      MEMORY_MANAGEMENT_SIZE_TEST: 900
      MEMORY_MANAGEMENT_SIZE_TRAIN: 300
      MEMORY_MANAGEMENT_TYPE: greedy
      MHA: false
      MIN_OFFSET: 0
      RATIO: 0.2
      REF_NUM_GLOBAL: 4
      REF_NUM_LOCAL: 2
      REF_NUM_MEM: 3
      SHUFFLED_CUR_TEST: false
    METHOD: diffusion
    RDN:
      ALL_FRAME_INTERVAL: 37
      KEY_FRAME_LOCATION: 18
      MAX_OFFSET: 18
      MIN_OFFSET: -18
      RATIO: 0.2
      REF_NUM: 2
    ROI_BOX_HEAD:
      ATTENTION:
        ADVANCED_STAGE: 0
        EMBED_DIM: 64
        ENABLE: false
        GROUP: 16
        STAGE: 1
      REDUCE_CHANNEL: false
    RPN:
      REF_POST_NMS_TOP_N: 75
      REF_PRE_NMS_TOP_N: 6000
  WEIGHT: pth/DiffusionVID_R101.pth
OUTPUT_DIR: training_dir/vid_R_101_DiffusionVID_gaode_4
PATHS_CATALOG: /data1/jiahaoguo/DiffusionVID/mega_core/config/paths_catalog.py
SOLVER:
  ACCUMULATION_STEPS: 2
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.0001
  BATCH_REUSE_STEPS: 1
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 3
  LR_SCHEDULER_TYPE: step
  MAX_ITER: 65000
  MOMENTUM: 0.9
  OPTIMIZER: ADAMW
  OPTIMIZER_TYPE: adamw
  STEPS:
  - 40000
  - 60000
  TEST_PERIOD: 5000
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 13727
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TENSORBOARD: true
TEST:
  BBOX_AUG:
    ENABLED: false
    H_FLIP: false
    MAX_SIZE: 4000
    SCALES: []
    SCALE_H_FLIP: false
  DETECTIONS_PER_IMG: 300
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 3
  SEQ_NMS: false
